// Analysis-ready bundle (spec §3.6): data + codebook + auto-generated
// R/Python loader scripts + README, zipped. Pure: takes a profile's output
// and returns the archive bytes.
import { buildCodebook } from "../objects/codebook.ts";
import { csvSerialize } from "./csv.ts";
import type { ExportProfile, ProfileOutput } from "./profiles.ts";
import { zipStore } from "./zip.ts";

function rLoader(): string {
  return `# Auto-generated by StudyHub. Reads the bundled data file.
# Usage: source("load.R"); head(data)
data <- read.csv("data.csv", stringsAsFactors = FALSE)
codebook <- jsonlite::fromJSON("codebook.json")
`;
}

function pyLoader(): string {
  return `# Auto-generated by StudyHub. Reads the bundled data file.
# Usage: from load import data, codebook
import csv
import json

with open("data.csv", newline="", encoding="utf-8") as f:
    data = list(csv.DictReader(f))
with open("codebook.json", encoding="utf-8") as f:
    codebook = json.load(f)
`;
}

function readme(opts: {
  datasetName: string;
  studyName: string;
  profile: ExportProfile;
  rows: number;
  exportedAt: Date;
}): string {
  const profileNote = opts.profile === "full"
    ? "FULL export (PI-only): stable pseudonymous participant codes and collection metadata included."
    : opts.profile === "de_identified"
    ? "DE-IDENTIFIED export: participant ids are fresh per-export labels; rows are shuffled; no collection metadata."
    : "OSF-READY export: de-identified, with open-ended text columns removed.";
  return `${opts.datasetName} — ${opts.studyName}
Exported ${opts.exportedAt.toISOString()} by StudyHub.

${profileNote}
Pilot-quarantined records are ${
    opts.profile === "full" ? "flagged via is_pilot" : "excluded"
  }.
Rows: ${opts.rows}

Files:
  data.csv       the records
  codebook.json  per-variable types, missingness, value inventories
  load.R         R loader (needs jsonlite for the codebook)
  load.py        Python loader (stdlib only)
`;
}

export function buildBundle(opts: {
  datasetName: string;
  studyName: string;
  profile: ExportProfile;
  output: ProfileOutput;
  exportedAt: Date;
}): Uint8Array {
  const { columns, rows } = opts.output;
  return zipStore([
    { name: "data.csv", content: csvSerialize(columns, rows) },
    {
      name: "codebook.json",
      content: JSON.stringify(buildCodebook(rows), null, 2) + "\n",
    },
    { name: "load.R", content: rLoader() },
    { name: "load.py", content: pyLoader() },
    {
      name: "README.txt",
      content: readme({
        datasetName: opts.datasetName,
        studyName: opts.studyName,
        profile: opts.profile,
        rows: rows.length,
        exportedAt: opts.exportedAt,
      }),
    },
  ]);
}
