// Shareable design one-pager (spec §3.2): a clean, print-friendly render
// of the structured design that feeds the IRB draft. No app chrome.
import { HttpError, page } from "fresh";
import type { ComponentChildren } from "preact";
import { define } from "../../../utils.ts";
import { getDb } from "../../../lib/db/client.ts";
import type { Condition } from "../../../lib/db/schema.ts";
import {
  getStudyFor,
  type StudyWithProject,
} from "../../../lib/objects/studies.ts";
import { listConditions } from "../../../lib/objects/design.ts";
import { statusView } from "../../../lib/ooui/status.ts";
import { PilotBanner } from "../../../components/ooui/PilotBanner.tsx";

interface Data {
  found: StudyWithProject;
  conditions: Condition[];
}

export const handler = define.handlers({
  async GET(ctx) {
    const db = getDb();
    const found = await getStudyFor(db, ctx.state.member!, ctx.params.id);
    if (!found) throw new HttpError(404);
    return page<Data>({
      found,
      conditions: await listConditions(db, found.study.id),
    });
  },
});

function Lines(props: { text: string }) {
  const lines = props.text.split("\n").map((l) => l.trim()).filter(Boolean);
  if (lines.length === 0) return <p class="text-gray-400">—</p>;
  if (lines.length === 1) return <p>{lines[0]}</p>;
  return (
    <ul class="list-disc pl-5">
      {lines.map((line, i) => <li key={i}>{line}</li>)}
    </ul>
  );
}

function Section(props: {
  title: string;
  children: ComponentChildren;
}) {
  return (
    <section class="mt-5">
      <h2 class="mb-1 text-xs font-bold uppercase tracking-wide text-gray-500">
        {props.title}
      </h2>
      <div class="text-sm leading-relaxed text-gray-900">{props.children}</div>
    </section>
  );
}

// Server-rendered inline handler, spread because Preact's types only accept
// function-typed onClick (same pattern as ActionBar's confirm onsubmit).
const printOnClick = { onclick: "window.print()" };

export default define.page<typeof handler>(({ data }) => {
  const { study, project } = data.found;
  return (
    <main class="mx-auto max-w-3xl p-8 print:p-0">
      <div class="mb-6 flex items-center justify-between print:hidden">
        <a
          href={`/studies/${study.id}?tab=design`}
          class="text-sm text-brand-700 hover:underline"
        >
          ← Back to study
        </a>
        <button
          type="button"
          class="rounded-card border border-gray-300 px-3 py-1.5 text-sm hover:bg-gray-50"
          {...printOnClick}
        >
          Print / save as PDF
        </button>
      </div>

      {study.oversightPathway === "internal_pilot" && (
        <div class="mb-4">
          <PilotBanner />
        </div>
      )}
      <header class="border-b border-gray-300 pb-4">
        <p class="text-xs uppercase tracking-wide text-gray-500">
          Study design one-pager · {project.name}
        </p>
        <h1 class="mt-1 text-2xl font-bold">{study.name}</h1>
        <p class="mt-1 text-sm text-gray-600">
          {study.methodology.replaceAll("_", " ")} ·{" "}
          {statusView(study.oversightPathway).label} · status{" "}
          {statusView(study.status).label}
          {study.designType && <>· {study.designType}-subjects design</>}
          {study.targetN !== null && <>· target N = {study.targetN}</>}
        </p>
      </header>

      {study.description && (
        <Section title="Summary">
          <p class="whitespace-pre-wrap">{study.description}</p>
        </Section>
      )}
      <Section title="Research questions">
        <Lines text={study.researchQuestions} />
      </Section>
      <Section title="Hypotheses">
        <Lines text={study.hypotheses} />
      </Section>
      <div class="grid grid-cols-2 gap-6">
        <Section title="Independent variables">
          <Lines text={study.independentVariables} />
        </Section>
        <Section title="Dependent variables">
          <Lines text={study.dependentVariables} />
        </Section>
      </div>
      <Section title="Conditions">
        {data.conditions.length === 0
          ? <p class="text-gray-400">—</p>
          : (
            <ol class="list-decimal pl-5">
              {data.conditions.map((c) => <li key={c.id}>{c.name}</li>)}
            </ol>
          )}
      </Section>
      <Section title="Exclusion criteria">
        <Lines text={study.exclusionCriteria} />
      </Section>
      {study.counterbalancingScheme && (
        <Section title="Counterbalancing scheme">
          <p class="whitespace-pre-wrap">{study.counterbalancingScheme}</p>
        </Section>
      )}

      <footer class="mt-8 border-t border-gray-200 pt-2 text-xs text-gray-400">
        Generated by StudyHub on {new Date().toISOString().slice(0, 10)}
      </footer>
    </main>
  );
});
